export const LCD_DIGIT_MATRIX:Array<Array<boolean>> = [
    [true,true,true,true,true,
     true,false,false,false,true,
     true,false,false,false,true,
     true,false,false,false,true,
     true,false,false,false,true,
     true,false,false,false,true,
     true,true,true,true,true],

    [false,false,false,true,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true],

    [true,true,true,true,true,
     false,false,false,false,true,
     false,false,false,false,true,
     true,true,true,true,true,
     true,false,false,false,false,
     true,false,false,false,false,
     true,true,true,true,true],

    [true,true,true,true,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,true,true,true,
     false,false,false,false,true,
     false,false,false,false,true,
     true,true,true,true,true],

    [true,false,false,false,false,
     true,false,false,false,true,
     true,false,false,false,true,
     true,true,true,true,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true],

    [true,true,true,true,true,
     true,false,false,false,false,
     true,false,false,false,false,
     true,true,true,true,true,
     false,false,false,false,true,
     false,false,false,false,true,
     true,true,true,true,true],

    [true,true,true,true,true,
     true,false,false,false,true,
     true,false,false,false,false,
     true,true,true,true,true,
     true,false,false,false,true,
     true,false,false,false,true,
     true,true,true,true,true],

    [true,true,true,true,true,
     true,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true,
     false,false,false,false,true],

    [true,true,true,true,true,
     true,false,false,false,true,
     true,false,false,false,true,
     true,true,true,true,true,
     true,false,false,false,true,
     true,false,false,false,true,
     true,true,true,true,true],

    [true,true,true,true,true,
     true,false,false,false,true,
     true,false,false,false,true,
     true,true,true,true,true,
     false,false,false,false,true,
     false,false,false,false,true,
     true,true,true,true,true],

    [false,false,false,false,false,
     false,false,false,false,false,
     false,false,false,false,false,
     false,false,false,false,false,
     false,false,false,false,false,
     false,false,false,false,false,
     false,false,false,false,false]
];
